### PR TITLE
py-client: make iteration order over entities in map deterministic

### PR DESCRIPTION
**Pull request by Snaar**
Further progress on the quest for no quant diffs between client languages.

### CODE REVIEW

**Comment by Snaar** [comment]
It's a bit nuanced - OrderedDict would make iteration identical to order entities were mentioned on the update string from the engine, not necessarily same as if you sort it. I'm not sure if this has that much overhead. In Java using LinkedHashMap vs HashMap isn't such a big deal - they are both horribly slow.

**Comment by Snaar** [comment]
In cpp bot I went for vector that has all the data and then there is separate map if you really do want to look stuff up using IDs.

**Comment by Snaar** [comment]
Hm. Internet suggests that Python 3.6 dict is already sorted by insertion order out of the box. I've been testing on 3.5 locally. What version do we use on the workers?

**Comment by j-clap** [comment]
I haven't profiled it, but I don't assume it'd be much slower, especially considering ships are <<1000, so I'm assuming worst case a 10x iterations diff, but those would be less heavy than the heavier part (create/delete). Anyway, not terrible, shouldn't affect this runtime much.

**Comment by j-clap** [comment]
3.5 lat I checked, but we were about to update

**Comment by Snaar** [comment]
Ok so this possibly becomes moot if update to 3.6 happens. Let me get 3.6 and test first and then there would be no need for this change.

**Comment by Janzert** [comment]
Default python version used to run bots on workers is now 3.6. So dictionaries should be preserving insertion order.

Python 3.5 is still used for running the actual worker scripts though, but that makes no difference for this.

**Comment by j-clap** [comment]
Thank you @Janzert. As such I think we can close this one

**Comment by Snaar** [comment]
Yeah, sweet, just tested, works as advertized.

**Pull request closed without merging**
