### PR TITLE
Support REQUIRE for Julia (fixes #218)

### LINKED ISSUE #218: Support Julia package management in compilation
https://forums.halite.io/t/julia-starter-kit-broken/437/6

### PR DESCRIPTION
**Pull request by lidavidm**

### CODE REVIEW

**Comment by Snaar** [comment]
Looks good to me, but I lack depth of knowledge of that part of Halite :-(

**Comment by j-clap** [comment]
I sadly lack the knowledge in Julia :/

**Comment by Snaar** [comment]
Can you at least be confident it doesn't break rest of the system? I think person who uses Julia will be able to provide feedback on that once they try to actually submit the bots.

**Comment by j-clap** [comment]
Yes, this won't adversely affect anything else. Just not sure how effective it'll be for Julia.

**Comment by Snaar** [comment]
@lidavidm @harikmenon I think this means that we are ok merging it in

**Comment by Snaar** [comment]
Ok let's just merge it in and let it rip.

**Pull request merged**
