### PR TITLE
Add winter's and New Year's planets

### PR DESCRIPTION
**Pull request by lidavidm**
download 17
download 16

### CODE REVIEW

**Comment by lidavidm** [comment]
@julskast how does this look?

**Comment by julskast** [comment]
Looks nice @lidavidm.  @j-clap which one do you like better? I say the first one is clearer - definitely winter!

**Comment by lidavidm** [comment]
Right now it (should) automatically switch over once the new year starts,
as another option.

**Comment by j-clap** [comment]
I like the [first one](https://user-images.githubusercontent.com/327919/33968851-2b0aa5dc-e038-11e7-840e-b2bac31f9bc6.png) the most. They're loverly.

**Comment by julskast** [comment]
@lidavidm switch over from what to what and on what day?

I'd be ok with using the winter one from Dec 23-Dec 30 and the other second one from Dec 31-Jan 1, but only if that's easy to do. Otherwise should just be the winter one (the first one) from Dec 23-Jan 1.

Thanks!

**Comment by lidavidm** [comment]
Right now it changes from the winter image to the New Year's image on midnight Jan 1, but I can adjust the dates.

**Comment by julskast** [comment]
Awesome, so yeah @lidavidm let's adjust the dates as I specified if you don't mind. Other than that, good to go!

**Comment by lidavidm** [comment]
No problem, it's been updated!

**Pull request merged**
