### PR TITLE
Add Ruby starter bot base files

### PR DESCRIPTION
**Pull request by jenheilemann**
I'm using ruby 2.4.2.

### CODE REVIEW

**Comment by jenheilemann** [comment]
HMU if you need anything, I'm Jen#6512 on discord (jheilema).

**Comment by harikmenon** [comment]
@jenheilemann can you do a pull and merge from master. Travis is breaking on your PR

**Comment by jenheilemann** [comment]
I'm up to date on my master branch with the main one. Master is broken, I think?

**Comment by harikmenon** [comment]
You are correct, I had fixed it locally, didnt push it. Just pushed.

**Comment by jenheilemann** [comment]
Yay! thanks!

**Comment by wimrijnders** [comment]
@jenheilemann You beat me to it by a matter of minutes! But your starter kit is better than mine, so I can find acceptance.

Just wanted to greet you. It appears that at time of writing we are still the only two rubyists in the challenge. I'm on a mission (again) to prove that ruby can be competitive.

**Pull request merged**
